### ISSUE TITLE
Readme indicates the use of a command that may not work

### ISSUE THREAD

**Issue by dferramosi** [connoryates/dotfiles#1]
if brew bundle isn't already installed then `brew install` with no arguments doesn't work. If the readme instead says to use `brew bundle install` this will work whether or not you have brew bundle installed

https://github.com/connoryates/dotfiles/blob/0c85d43476d6bc45eea43de82391e1ec00a6c2d7/README.md?plain=1#L7

**Comment by connoryates** [comment]
fixed in [8702118](https://github.com/connoryates/dotfiles/commit/8702118f22075fa439031bf398a96f3c65528cd3)
